---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secret.dockercred.name }}-{{ .Release.Name }}
    namespace: {{ .Values.namespace.name }}
    labels:
     {{- include "notifier.labels" . | nindent 5 }}
data:
    .dockerconfigjson: {{ .Values.secret.dockercred.dockerconfigjson }}
type: {{ .Values.secret.dockercred.type }}

---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secret.rdscred.name }}-{{ .Release.Name }}
    namespace: {{ .Values.namespace.name }}
    labels:
     {{- include "notifier.labels" . | nindent 5 }}
type: {{ .Values.secret.rdscred.type }}
data:
    username: {{ .Values.secret.rdscred.username }}
    password: {{ .Values.secret.rdscred.password }}